import { useState } from 'react';
import { CircleAlert, Lightbulb, Sparkles, Wand2 } from 'lucide-react';

import type { Review } from '../types';

type Props = {
  review: Review;
};

/** Three bands, so a weak score reads as weak without comparing the numbers. */
function tier(value: number): string {
  if (value <= 4) return 'tier-low';
  if (value <= 7) return 'tier-mid';
  return 'tier-high';
}

function Score({ label, value }: { label: string; value: number }) {
  return (
    <div className={'score-card ' + tier(value)}>
      <div>
        <span>{label}</span>
        <b>{value}/10</b>
      </div>
      <div className="bar">
        <i style={{ width: `${Math.max(0, Math.min(100, value * 10))}%` }} />
      </div>
    </div>
  );
}

export default function ReviewPanel({ review }: Props) {
  // The plan asks for a hint *before* a full solution, so both of these
  // start collapsed and are revealed only on request.
  const [showHint, setShowHint] = useState(false);
  const [showApproach, setShowApproach] = useState(false);

  return (
    <section className="review-panel">
      <div className="review-title">
        <div>
          <h2>Feedback on your approach</h2>
          {review.source === 'heuristic' && (
            <p className="review-source">
              Rule-based review — add a GEMINI_API_KEY to the backend for model-generated feedback.
            </p>
          )}
          {review.source === 'groq' && (
            <p className="review-source">
              Generated by the Groq fallback — Gemini was unavailable for this request.
            </p>
          )}
        </div>
        <div className={'score ' + tier(review.overall_score)}>
          <strong>{review.overall_score}</strong>
          <span>/ 10</span>
        </div>
      </div>

      <div className="score-grid">
        <Score label="Correctness" value={review.correctness_score} />
        <Score label="Readability" value={review.readability_score} />
        <Score label="Efficiency" value={review.efficiency_score} />
      </div>

      <div className="review-body">
        <div className="review-main">
          <p>{review.summary}</p>

          {review.issues.map((issue, index) => (
            <div className="issue" key={index}>
              <span className="issue-icon">
                <CircleAlert size={16} />
              </span>
              <div>
                <b>{issue.title}</b>
                <p>{issue.explanation}</p>
              </div>
            </div>
          ))}

          {review.suggestions.length > 0 && (
            <div className="suggestion">
              <Sparkles size={17} />
              <div>
                <b>{review.suggestions.length > 1 ? 'Suggestions' : 'Suggestion'}</b>
                <ul className="suggestion-list">
                  {review.suggestions.map((suggestion, index) => (
                    <li key={index}>{suggestion}</li>
                  ))}
                </ul>
              </div>
            </div>
          )}
        </div>

        <aside className="complexity">
          <h4>Complexity</h4>
          <div>
            <span>Current time</span>
            <b>{review.complexity.current_time}</b>
          </div>
          <div>
            <span>Current space</span>
            <b>{review.complexity.current_space}</b>
          </div>
          <div className="divider" />
          <div>
            <span>Suggested time</span>
            <b>{review.complexity.suggested_time}</b>
          </div>
          <div>
            <span>Suggested space</span>
            <b>{review.complexity.suggested_space}</b>
          </div>

          <button className="hint-btn" onClick={() => setShowHint((value) => !value)}>
            <Lightbulb size={15} /> {showHint ? 'Hide Hint' : 'Show Hint'}
          </button>
          {showHint && <p className="hint-text">{review.hint}</p>}

          {review.improved_approach && (
            <>
              <button className="hint-btn" onClick={() => setShowApproach((value) => !value)}>
                <Wand2 size={15} />{' '}
                {showApproach ? 'Hide Improved Approach' : 'View Improved Approach'}
              </button>
              {showApproach && <p className="hint-text">{review.improved_approach}</p>}
            </>
          )}
        </aside>
      </div>
    </section>
  );
}
